"""add_milestones_and_bug_milestone_id

Revision ID: 71dee8c46579
Revises: 8d9b9e8c1103
Create Date: 2026-03-03 13:50:58.512421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71dee8c46579'
down_revision: Union[str, None] = '8d9b9e8c1103'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('milestones',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('bugs', sa.Column('milestone_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'bugs', 'milestones', ['milestone_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bugs', type_='foreignkey')
    op.drop_column('bugs', 'milestone_id')
    op.drop_table('milestones')
    # ### end Alembic commands ###
